### ISSUE TITLE
CutInterface doesn't work in some installations (related to missing video acceleration?)

### ISSUE THREAD

**Issue by gCurse** [EinApfelBaum/otr-verwaltung3p#10]
When opening the Cutinterface in virtualbox the video is displayed in a separate "OpenGL-renderer" window aside of the Cutinterface. Navigation buttons do work.

This can be fixed by adding the following code after line ~220: `self.playbin = Gst.ElementFactory.make('playbin', None)`
```
self.videosink = Gst.ElementFactory.make("ximagesink", "ximagesink")
self.playbin.set_property("video-sink", self.videosink)
```
Cutinterface of otrv++ works in virtualbox.

**Comment by gCurse** [comment]
Thanks for the quick close and reply. I changed the issue title to fit your report.
@EinApfelBaum can you share some insights on this? (works for me)

**Comment by dietmarw** [comment]
```
$ uname -srvmpio
Linux 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
glxinfo: 
https://gist.github.com/dietmarw/c4fa8e8d9f10ed67f752652963af0124

**Comment by EinApfelBaum** [comment]
I remember this kind of behaviour in some testing situation, this was last year.
I will think about it.

I also have problems with the cutinterface, that could have the same cause.

My problem is that the CutInterface is not showing the video. 
Audio and navigation is working.
https://gist.github.com/EinApfelBaum/5c27c48f31625f9e94450cf4c85419e1

Until now I could not figure out the problem.
My last thougth was, that is some hardware / kernel issue.

```
$ uname -srvmpio
Linux 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by gCurse** [comment]
@dietmarw I pushed a new branch containing a workaround for this issue: 04-26_workaround-no-xv
It adds the cli option -n or --noxv. Please test this new branch and report back. Thanks.
```
git pull
git fetch
git checkout -b 04-26_workaround-no-xv
```
You are now on the new branch. Start otr-verwaltung like so:
`bin/otrverwaltung --noxv`

@EinApfelBaum Whenever faced an empty video window it was caused by a missing dependency.
Did you try to run installscripts/otrv3p-install-deb.sh?

**Comment by dietmarw** [comment]
@gCurse the no-xv switch did not open the extra video window but the frame only displays a frozen version of the desktop at the place where the cut assistant window was opened.

**Comment by gCurse** [comment]
@dietmarw Please run installscripts/otrv3p-install-deb.sh again to make sure all known dependencies are installed.
I attached a python video player. Would you please test it?
Start the program, paste full path to an otr-video into the entry field at the top and press play.
If this plays the video we can use it as a reference.
BTW this is my modified version of https://github.com/gkralik/python-gst-tutorial/blob/master/basic-tutorial-5.py

**Comment by gCurse** [comment]
Last one. Terminal output of
`GST_DEBUG=2 ~/otr-verwaltung3p/bin/otrverwaltung --noxv`
until the cutinterfacedialog shows up and then one play ... pause, please. Thanks.

**Comment by dietmarw** [comment]
https://gist.github.com/dietmarw/cbdd1be7fbc99f63a9899940998029ec

**Comment by EinApfelBaum** [comment]
@gCurse no, I installed all packages manual.
I tried to run the script, but got some errors.
I am too tired rigth now and cant get focused and concentrade.
In this moment i am the failure. =D

**Comment by gCurse** [comment]
I pushed a new branch: early_playbin which should at least handle the no xvideo issue
Please test this new branch and report back. Thanks.
```
git fetch
git checkout -b early_playbin
```
@dietmarw @EinApfelBaum

**Comment by dietmarw** [comment]
Almost now. It displays the video player inside the interface now. If the frame does not fit the movie than a transparent background is shown. I could live with that but if you like you could make that part non-transparent with the app window background.

![image](https://user-images.githubusercontent.com/9332/39361671-cd2e7406-4a23-11e8-8dda-4d74f183e120.png)

**Comment by gCurse** [comment]
Good news!
Please have a look at your conf file and search for cutinterface_resolution_x and cutinterface_resolution_y.
Make sure the ratio of x and y is 16:9, something like 800x450.
I'll look into making the background solid black.

**Comment by dietmarw** [comment]
That did it :-) So I'd say this is good to merge.

**Comment by gCurse** [comment]
Before merging I'll make change to force 16:9 by ignoring cutinterface_resolution_y
And if you ever stumble upon a 4:3 video, please
`killall <your compositor>` ;)

**Comment by dietmarw** [comment]
Thanks guys. This was really quick!

**Comment by EinApfelBaum** [comment]
Soo, the install script was successful running through. ( I messed up my system with printer drivers, now its clear )
With the early playbin branch its look like this. Screen is black and audio is running.

Cutinterace resolution 800x450

![cutinterfaceblackscreen](https://user-images.githubusercontent.com/4492357/39393540-be8e9c48-4ac6-11e8-89ae-7006b728e912.png)

**Comment by gCurse** [comment]
But [basic-tutorial-5-play-local-file.py.txt](https://github.com/EinApfelBaum/otr-verwaltung3p/files/1951463/basic-tutorial-5-play-local-file.py.txt) plays the file?
Well, I'm out of ideas for now. Sorry.
Maybe you should open an issue for this?

**Comment by EinApfelBaum** [comment]
Yea this is working, I will open a new issue for that, becaus that one is finsihed.
Yea I am out of ideas too, last year I also tried everthing and I dont know why it is not working.

Thanks.
