### ISSUE TITLE
otrv3p-install-opensuse_leap.sh: Zeile 157: check_pack: Kommando nicht gefunden.

### ISSUE THREAD

**Issue by radlwadl** [EinApfelBaum/otr-verwaltung3p#100]
Hello,

two errors in otrv3p-install-opensuse_leap.sh:

1. My openSUSE runs with a german localization. So the "zypper repos" gives a "Ja" instead of a "Yes" for an installed package. I fixed that in line 157 with a shortly hacked regex. Please see line below

2.  Script threw the error "Zeile 157: check_pack: Kommando nicht gefunden."
This is caused by leading and trainling spaces at the "="
Old
157  check_pack = $(zypper repos | grep -i packman | grep -i Yes )

New:
157  check_pack=$(zypper repos | grep -i packman | grep -Ei "Ja|Yes" )

> cat /etc/SUSE-brand 
openSUSE
VERSION = 15.0

Regards,
Chris

**Comment by gCurse** [comment]
Done. Thanks :)
I won't change the master branch, as the current versions of the scripts are hosted [here](https://github.com/gCurse/support/tree/master/otrv3p_installation_scripts).

Changed the file there.
