### ISSUE TITLE
solved: PyGTK/GTK is missing

### ISSUE THREAD

**Issue by m23project** [EinApfelBaum/otr-verwaltung3p#102]
Hi,

I installed otr-verwaltung3p with otrv3p-install-deb.sh on a minimal Ubuntu 18.04 system and got the error message "PyGTK/GTK is missing".

After installing the package "gir1.2-gtk-3.0" it runs.

I would be nice, if you could add the installation of "gir1.2-gtk-3.0" in otrv3p-install-deb.sh.

Thanks for your work,
 Hauke

**Comment by gCurse** [comment]
Thanks for your report. I will add "gir1.2-gtk-3.0" as a dependency.
* Can you please tell me which distribution (including the version) and desktop environment you are using?
* Did you know? We have packages now: [otr-verwaltung3p-dev_1.0.0-beta002ubuntu1804-py36.deb](https://github.com/EinApfelBaum/otr-verwaltung3p/releases/download/1.0.0-beta002/otr-verwaltung3p-dev_1.0.0-beta002ubuntu1804-py36.deb) and [otr-verwaltung3p-dev_1.0.0-beta002ubuntu1910-py37.deb](https://github.com/EinApfelBaum/otr-verwaltung3p/releases/download/1.0.0-beta002/otr-verwaltung3p-dev_1.0.0-beta002ubuntu1910-py37.deb) in the [release section](https://github.com/EinApfelBaum/otr-verwaltung3p/releases) (even though the dependency is missing in these packages, too) so the scripts will soon be obsolete.
