### ISSUE TITLE
Schneiden bleibt stehen

### ISSUE THREAD

**Issue by m23project** [EinApfelBaum/otr-verwaltung3p#104]
Hallo,

beim Versuch, einige Dateien (z.B. Brokenwood_Mord_in_Neuseeland_20.05.31_21-45_ard_90_TVOON_DE.mpg.HD.avi) nach dem Dekodieren zu schneiden, bleibt der Statusbalken in der Oberfläche stehen. Auf der Kommandozeile gibt es folgenden Stacktrace: 

Traceback (most recent call last):
  File "/home/user/otr-verwaltung3p/otrverwaltung/gui/MainWindow.py", line 740, in _on_toolbutton_clicked
    self.app.perform_action(action, cut_action)
  File "./otr-verwaltung3p/bin/otrverwaltung", line 679, in perform_action
    action.do(chosen_action, filenames, cut_action)
  File "/home/user/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 82, in do
    if self.cut(file_conclusions, action, cut_action) == False:
  File "/home/user/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 403, in cut
    file_conclusion.cut.cutlist, None)
  File "/home/user/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 543, in cut_file_by_cutlist
    cut_video, error = cutter.cut_file_by_cutlist(filename, cutlist)
  File "/home/user/otr-verwaltung3p/otrverwaltung/actions/cutsmartmkvmerge.py", line 117, in cut_file_by_cutlist
    self.config.get('smartmkvmerge', 'ffmpeg_hd_x264_options').split(' '), filename)
  File "/home/user/otr-verwaltung3p/otrverwaltung/actions/cut.py", line 591, in ffmpeg_codec_options
    codec_core = int(self.media_info.tracks[1].writing_library.split(' ')[2])
AttributeError: 'NoneType' object has no attribute 'split'

"file" gibt folgendes aus:
Brokenwood_Mord_in_Neuseeland_20.05.31_21-45_ard_90_TVOON_DE.mpg.HD.avi: RIFF (little-endian) data, AVI, 1280 x 720, >30 fps, video: H.264 X.264 or H.264, audio: MPEG-1 Layer 3 (stereo, 48000 Hz)

Auf dem Rechner läuft Ubuntu 18.04.4 LTS.

Wäre toll, wenn Ihr das korrigieren könntet :-)

Cu Hauke

**Comment by gCurse** [comment]
Stelle sicher, dass Du die neueste Version verwendest [otr-verwaltung3p-dev-1.0.0b7.deb](https://github.com/EinApfelBaum/otr-verwaltung3p/releases/download/1.0.0b7/otr-verwaltung3p-dev-1.0.0b7.deb)

- otrv3p beenden
- Öffne `~/.config/otrverwaltung3p/conf` in einem Texteditor
- Suche nach `encoder_engine` und ändere in dieser Zeile `ffmpeg` zu `x264`
- Speichere die Datei
- Teste das Schneiden des Videos
##### Wenn noch immer nicht funktioniert:
- otrv3p beenden
- Lösche `~/.config/otrverwaltung3p/conf`
- Starte otrv3p und gib alle benötigten Daten ein
- Teste das Schneiden des Videos

##### Beachte: Problem beim Schneiden des neuen HD-Formates mit dem Cutinterface:
Nach meinem letzten Test muss man die Schnittpunkte wie folgt setzen:
Anfang des Schnittes (Werbung): Den letzten Frame markieren, der bleiben soll.
Ende des Schnittes (Werbung): Zum ersten Frame der bleiben soll navigieren, dann weitere zwei Frames vorwärts und den Schnittpunkt setzen.

In der nächsten Version sollte der Fehler "zumindest fast" behoben sein.
#### _
##### English
Make sure you are using the latest version [otr-verwaltung3p-dev-1.0.0b7.deb](https://github.com/EinApfelBaum/otr-verwaltung3p/releases/download/1.0.0b7/otr-verwaltung3p-dev-1.0.0b7.deb)

- Stop otrv3p
- Open `~/.config/otrverwaltung3p/conf` in a text editor
- Search for `encoder_engine` and in this line change `ffmpeg` to `x264`
- Save the file
- Test cutting your video
##### If it still does not work:
- Stop otrv3p
- Delete `~/.config/otrverwaltung3p/conf`
- Start otrv3p and fill in all needed data
- Test cutting your video
