### ISSUE TITLE
Can't cut HD Files

### ISSUE THREAD

**Issue by Master-2000** [EinApfelBaum/otr-verwaltung3p#105]
When I try to cut a HD file I got following stack-trace:

```
otr-verwaltung3p, version 1.0.0-beta002
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/gui/MainWindow.py", line 753, in _on_toolbutton_clicked
    self.app.perform_action(action, cut_action)
  File "/usr/bin/otrverwaltung3p", line 688, in perform_action
    action.do(chosen_action, filenames, cut_action)
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/actions/decodeorcut.py", line 85, in do
    if self.cut(file_conclusions, action, cut_action) == False:
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/actions/decodeorcut.py", line 430, in cut
    cut_video, ac3_file, error = self.cut_file_by_cutlist(file_conclusion.uncut_video,
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/actions/decodeorcut.py", line 576, in cut_file_by_cutlist
    cut_video, error = cutter.cut_file_by_cutlist(filename, cutlist)
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/actions/cutsmartmkvmerge.py", line 116, in cut_file_by_cutlist
    codec, codec_core = self.ffmpeg_codec_options(
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/actions/cut.py", line 622, in ffmpeg_codec_options
    if 'x264' in self.media_info.tracks[1].writing_library:
TypeError: argument of type 'NoneType' is not iterable
```

Any idea? I installed it with https://aur.archlinux.org/packages/otr-verwaltung3p-dev/ on my arch linux system.

FFMPEG is installed:
```
ffmpeg version n4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 10.1.0 (GCC)
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```

**Comment by gCurse** [comment]
Please uninstall *otr-verwaltung3p-dev* and then install it again. You are stuck on an old version (latest is 1.0.0b8) and this seems related to the change in the versioning "style" (I think *1.0.0-beta002* is considered a higher version than *1.0.0b8*).

Please note that you (may?) have to re-create your configuration file
(Terminate otr-verwaltung3p and delete the configuration file: `mv $HOME/.config/otrverwaltung3p/conf $HOME/.config/otrverwaltung3p/conf.backup` then start otr-verwaltung3p again).

**Comment by Master-2000** [comment]
Thank you very much, the re-installation helps. Because I always have the highest version with my arch system, I don't look for the version. :laughing: 

Nice to see you answer so quickly.

**Comment by Master-2000** [comment]
Happy too early. Now I got:

> x264 [error]: Unknown demuxer `ffms'

But community/ffms2 2.23.1-4 is installed.

**Comment by gCurse** [comment]
Cutting does not work with the native Archlinux version of x264 as the ffms-demuxer is missing.
Try changing *Preferences->Schneiden->Kodierer* to ffmpeg

**Comment by Master-2000** [comment]
I got the same error with ffmpeg, but in the moment I want to share you a screenshot, I see that the file-ending was mkv. With the previous version I tried to convert the avi to mkv before cutting - but this also not worked.

With the current version the mkv produces the error with x264 and with ffmpeg, but I bring back the original avi (with ac3) and tried it again. And yeah, it works (also with x264).

So my original problem is solved with your help, but anyway the error exist while cutting a (HD) mkv. Your free to close the ticket, if the other problem is known.

Thank you :)

**Comment by gCurse** [comment]
Ah, now I remember:
When cutting a New-HD-format.mkv, x264 is forcibly used for smart-rendering as I cannot get it to work with ffmpeg. :(
When cutting a New-HD-format.avi, ffmpeg is forcibly used for smart-rendering as I cannot get it to work with x264. :(

Converting New-HD files to mkv before cutting is not supported.
