### ISSUE TITLE
Einfach mal Danke sagen

### ISSUE THREAD

**Issue by major-mayer** [EinApfelBaum/otr-verwaltung3p#106]
Ich weiß nicht wie ich es sonst übermittlen soll, aber ich wollte mich einfach nur für dieses großartige Programm bedanken.
Ich hatte vor meinem Umstieg auf Linux Bedenken ob ich dort Software für den OnlineTVRecorder finden werde.
Und was soll ich sagen: Alles funktioniert auf Anhieb und die Software bietet genau das was ich für meinen Workflow benötige in einem Programm vereint (dekodieren, schneiden, umbenennen).
Vielleicht habe ich es mir bis jetzt auch unnötig schwer gemacht, aber ein so gutes Programm kannte ich unter Windows nicht.

Vielen Dank für die großartige Arbeit, das Projekt ist einfach klasse :tada: :+1: 

PS: Der Dank geht natürlich an alle aktuellen und ehemaligen Entwickler ;)

**Comment by gCurse** [comment]
Vielen Dank für das Lob :)
