### ISSUE TITLE
installscript fails to log

### ISSUE THREAD

**Issue by DrVanScott** [EinApfelBaum/otr-verwaltung3p#112]
Hi,

the deb install script fails to log at least on mint, as root is not permitted to append to a tmp file of another user:

    $ id -u | tee -a /tmp/test.log
    1000
    $ sudo bash -c "id -u | tee -a /tmp/test.log"
    tee: /tmp/test.log: Permission denied
    0

**Comment by gCurse** [comment]
Did you use [otrv3p-install-deb-dev.sh](https://raw.githubusercontent.com/gCurse/support/master/otrv3p_installation_scripts/otrv3p-install-deb-dev.sh)? This is the newest version. Anything based on the master branch won't work.

**Comment by DrVanScott** [comment]
Yes i use the script you mentioned.
This seems to be related to the "fs.protected_regular" kernel parameter. On linux mint this is set to "2". The scenario described in my initial post can be reproduced after performing

    sudo sysctl fs.protected_regular=2

**Comment by gCurse** [comment]
I tried the script in an ubuntu 20.04 VM where fs.protected_regular is set to 2. It logs just fine.

In line 73 `chown root /tmp/otrv3p-install.log && chmod 666 /tmp/otrv3p-install.log` root takes ownership of the log-file and grants write permission to users.

**Comment by DrVanScott** [comment]
Your are right. Now i cannot reproduce the problem anymore. Sorry for this waste of time.

To at least provide a little bit, after a fresh clone of your support repository, some of the shell scripts are missing the executable permission, including otrv3p-install-deb-dev.sh

Thanks for your patience :-)
