### ISSUE TITLE
Installation, Befehl nicht gefunden

### ISSUE THREAD

**Issue by TerpenTH** [EinApfelBaum/otr-verwaltung3p#114]
Hallo Entwickler, 
**erstmal danke für dieses tolle Programm** (Nutze es auch unter Ubuntu).

Bei der installation mit dem otrv3p-install-opensuse_leap.sh script, traten 2 fehler auf!
```
2021-08-03_20:08:04 LOG BEGINS

otrv3p: Start sudo otrv3p-install-opensuse_leap.sh deps
otrv3p: Start otrv3p-install-opensuse_leap.sh prog
```

Packman ist aktiviert.
Meine Version OpenSuse Leap 15.3

**Comment by gCurse** [comment]
@TerpenTH Bitte poste die Terminal-Ausgabe, so dass ich die Fehlermeldungen sehen kann (persönliche Daten unkenntlich machen).

Danke.
