### ISSUE TITLE
Cut leads to audio-video sync problems

### ISSUE THREAD

**Issue by major-mayer** [EinApfelBaum/otr-verwaltung3p#116]
Hi,
I noticed this a few times already and thought that maybe it would be time for an Github report.
When i try to cut for example "Bad_Boys_II_20.12.27_22-25_sf2_145_TVOON_DE.mpg.HD.avi" using the cutlist from "Jojo17" or "McLANE" it leads to synchronization problems between the audio and the video track.
There video is lagging behind the audio for a few seconds, which makes it basically unwatchable.

Other movies where I noticed this are:
- Ostwind_2_20.12.26_09-25_ard_100_TVOON_DE.mpg.HD.avi
- John_Wick_21.09.12_22-10_orf1_95_TVOON_DE.mpg.HD.avi
- Der_Kautions_Cop_21.08.29_00-05_orf1_105_TVOON_DE.mpg.HD.avi

So only HD movies seem to be affected.
Is this a known problem? Could it be fixed somehow?

**Comment by Felerteufel** [comment]
Which OS?
Which Version (1.0.0b8.post4 ?)?

**Comment by major-mayer** [comment]
Ah sorry my fault.
OS is Manjaro 21.1.6
Version is `1.0.0b8.post4.r1.g3dbf46b`

**Comment by gCurse** [comment]
I experienced this too while testing HD but I don't know why this happens.

You have to cut those files with VirtualDub (wine).

Install **otr-verwaltung3p-vdub** (AUR).
otrv-settings: _Bearbeiten - Einstellungen - Schneiden_: Set **'HD neu 2020'** to **'intern-vdub'**

See also #115

**Comment by major-mayer** [comment]
I just installed the vdub package from the AUR and tried this method.
It works indeed, but feels a bit hacky.

Could you maybe add this information to the Wiki? This could prevent some unnecessary bug reports.
