### ISSUE TITLE
CutInterface GTK Version 3.20

### ISSUE THREAD

**Issue by EinApfelBaum** [EinApfelBaum/otr-verwaltung3p#50]
When i want to open the CutIntferace i got the following error:

> Traceback (most recent call last):
>   File "/home/baum/Entwicklung/otr-verwaltung3p/otrverwaltung/gui/MainWindow.py", line 669, in _on_toolbutton_clicked
>     self.app.perform_action(action, cut_action)
>   File "otrverwaltung", line 645, in perform_action
>     action.do(chosen_action, filenames, cut_action)
>   File "/home/baum/Entwicklung/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 82, in do
>     if self.cut(file_conclusions, action, cut_action) == False:
>   File "/home/baum/Entwicklung/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 323, in cut
>     error_message, cutlist = self.cut_file_manually(file_conclusion.uncut_video)
>   File "/home/baum/Entwicklung/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 463, in cut_file_manually
>     ci = CutinterfaceDialog.NewCutinterfaceDialog(self.gui)
>   File "/home/baum/Entwicklung/otr-verwaltung3p/otrverwaltung/gui/CutinterfaceDialog.py", line 1113, in NewCutinterfaceDialog
>     builder.add_from_file(glade_filename)
> GLib.Error: gtk-builder-error-quark: /home/baum/Entwicklung/otr-verwaltung3p/otrverwaltung/../data/ui/CutinterfaceDialog.glade:5:1 Required gtk+ version 3.20, current version is 3.18 (7)

It looks like the new CutIntferace has gtk version 3.20. Linux MInt 18.3 runs with gtk 3.18

**Comment by gCurse** [comment]
Please open `CutinterfaceDialog.glade` and `LoadCutDialog.glade` in glade and change the gtk version to 3.12 (Seems most if not all glade files are set to this version).
Please check if this solves the issue.

**Comment by EinApfelBaum** [comment]
Thanks, I also need to remove the property "propagate_natural_width" in line 521 for the GtkScrolledWindow control.
