### ISSUE TITLE
Decoding hangs

### ISSUE THREAD

**Issue by Steffen1989** [EinApfelBaum/otr-verwaltung3p#57]
When I decode an otrkey file on my arch linux Laptop, otr-verwaltung3p hangs.

The progress bar reaches 100% for "Eingabedatei 1/1 kontrollieren".
Via "top", I see that intern-otrdecoder is in zombie state and the process python3 uses 100% of CPU.

Running in verbose mode only shows this warning:
(otrverwaltung:13824): IBUS-WARNING **: 14:13:25.488: Unable to connect to ibus: Could not connect: Connection refused

Any ideas what might be causing this problem?

Edit:
Not using the intern-otrdecoder but a manually installed one works.

**Comment by gCurse** [comment]
I have no idea.
Can you shed some light on your edit?:
Does that mean the decoder works on the commandline but not when called from within otrv3p? Or did you replace intern-otrdecoder with manually installed and renamed decoder?

Does terminating ibus change anything?

Test: I installed and started ibus. otrv3p decodes files without error.

Would you mind trying otrtool (in AUR)? Install it and change prefs in otrv3p to use otrtool. Try decoding a file.

**Comment by Steffen1989** [comment]
Regarding my edit, I have replaced the file intern-otrdecoder in tools folder with a link to another decoder. Unfortunately, I could find out which one of those from https://www.onlinetvrecorder.com/v2/?go=software&tab=Linux it is.

When using otrtool from AUR, decoding also works. 

So for me problem is solved either using my manually installed decoder or otrtool. Thanks for the suggestion.

**Comment by gCurse** [comment]
If you want to find out which decoder you initially downloaded you can re-download them one by on (most likely first), unpack, and then compare the decoder to the working one (`cmp <file1> <file2>` This will either exit cleanly if they are binary equal, or it will print out where the first difference occurs and exit.)

The intern-otrdecoder in the repo is this one: [Statisch gelinkt, 64 Bit](http://www.onlinetvrecorder.com/downloads/otrdecoder-bin-64bit-linux-static-v519.tar.bz2) (otrdecoder-bin-64bit-linux-static-v519.tar.bz2)

**Comment by Steffen1989** [comment]
By using cmp, I found out that the decoder I had used initially, is the Easydecoder "Console version, 64bits".

**Comment by gCurse** [comment]
So, newest Easydecoder works for you and intern-otrdecoder does not.

I'll update the intern-easydecoder to the lastest version. Then you can select intern-easydecoder in preferences to be used for decoding.
