### ISSUE TITLE
Decode: error, when E-Mail and password is not set in config

### ISSUE THREAD

**Issue by EinApfelBaum** [EinApfelBaum/otr-verwaltung3p#58]
Install otr3p with the install script for ubuntu/linux mint.
At the first start I was asked, to set the location.
At the second start I was asked, to set E-Mail and Password.
When I click the decode button and I have not configured E-Mail and password i get this error:

> Traceback (most recent call last):
>   File "/home/baum/otr-verwaltung3p/otrverwaltung/gui/MainWindow.py", line 669, in _on_toolbutton_clicked
>     self.app.perform_action(action, cut_action)
>   File "otrverwaltung", line 645, in perform_action
>     action.do(chosen_action, filenames, cut_action)
>   File "/home/baum/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 77, in do
>     if self.decode(file_conclusions) == False:
>   File "/home/baum/otr-verwaltung3p/otrverwaltung/actions/decodeorcut.py", line 133, in decode
>     self.gui.dialog_email_password.set_email_password(email, password)
>   File "/home/baum/otr-verwaltung3p/otrverwaltung/gui/EmailPasswordDialog.py", line 38, in set_email_password
>     self.builder.get_object('entryDialogPassword').set_text(password.decode('utf-8'))
> AttributeError: 'str' object has no attribute 'decode'

Linux distro: Linux Mint 19

**Comment by gCurse** [comment]
I'll fix that in the next commit.
