### ISSUE TITLE
CutInterface with black Screen

### ISSUE THREAD

**Issue by EinApfelBaum** [EinApfelBaum/otr-verwaltung3p#68]
The CutInterface is not playing the video, drawingarea is black, but the audio is playing.

@gCurse can you pls run otr cutinterface in debugmode with the branch GstreamerDebug.
Maybe we can find the error im detail log. 
For more information we can change the log level.

Here is my logfile:
Gstreamer debug log with log level Error:
![gstreamererrordebuglog](https://user-images.githubusercontent.com/4492357/43102751-44ae1ecc-8ecc-11e8-8396-fb9dff1eb9ea.png)

**Comment by gCurse** [comment]
@EinApfelBaum I installed Mint19 to an empty partition on my computer. After having problems to graphically log into cinnamon (only startx worked) I installed lxde (`sudo apt install lxde`).

__And... otrv3p works perfectly!__

It doesn't work when logging into cinnamon (in my case via `startx`) --> black video window (well, it's an empty video window, as can be seen when commenting the stuff in `def on_draw_movie_window(self, widget, cr)`.
