### ISSUE TITLE
Installationsskript OpenSuse 15: Pfad führt ins Leere

### ISSUE THREAD

**Issue by anonvoy** [EinApfelBaum/otr-verwaltung3p#77]
Unter dem angegebenen Link https://raw.githubusercontent.com/einapfelbaum/otr-verwaltung3p/master/installscripts/otrv3p-install-opensuse_WIP.sh ist nichts.

**Comment by timo08** [comment]
https://github.com/EinApfelBaum/otr-verwaltung3p/raw/master/installscripts/otrv3p-install-opensuse_leap.sh

**Comment by gCurse** [comment]
I updated the links in the wiki.
