### ISSUE TITLE
Conf: TypeError: new() missing 1 required positional argument: 'mode'

### ISSUE THREAD

**Issue by gruenkaeppchen** [EinApfelBaum/otr-verwaltung3p#79]
Starting otr-verwaltung3p for the second time gives the following problem:

>Traceback (most recent call last):
>  File "./bin/otrverwaltung", line 1023, in <module>
>    app = App()
>  File "./bin/otrverwaltung", line 264, in __init__
>    self.config.load()
>  File "/home/username/otr-verwaltung3p/otrverwaltung/config.py", line 126, in load
>    decryption_suite = AES.new(base64.b64decode(json_config['general']['aes_key'].encode('utf-8')))
>TypeError: new() missing 1 required positional argument: 'mode'

Potential Solution:
add the AES.mode to the decryption_suite (otrverwaltung/config.py lines 89 and 126):
`encryption_suite = AES.new(base64.b64decode(self.__fields['general']['aes_key'].encode('utf-8')), AES.MODE_CBC)`
and
`decryption_suite = AES.new(base64.b64decode(json_config['general']['aes_key'].encode('utf-8')), AES.MODE_CBC)`

**Comment by gCurse** [comment]
@timo08 Can you take a look at this, please

**Comment by timo08** [comment]
> @timo08 Can you take a look at this, please. Seems [pycrypto](https://www.dlitz.net/software/pycrypto/) isn't developed any more? I changed to [pycryptodome](https://github.com/Legrandin/pycryptodome) and get the same error.

I'm trying to find a solution, give me some time :)

**Comment by gCurse** [comment]
@timo08 Can you have a look at this pure python AES implementation: [pyaes](https://github.com/ricmoo/pyaes) or something similar?
We could use it as an internal library (in the libs folder). That would be set and forget. And we'd get rid of one dependency.
I think I will make gitpython an internal library, too.

**Comment by gCurse** [comment]
Fixed in db3466bbf02a68e4ed6499e8a420bd08b3c21088
