### ISSUE TITLE
headless mode

### ISSUE THREAD

**Issue by tango25001** [EinApfelBaum/otr-verwaltung3p#87]
Is there a possibility to have otrkey files processed (decoded and cut if cutlist is available) without user interaction?

**Comment by gCurse** [comment]
No. It is GUI only.
But "without too much user interaction" you can try the batch mode:
1. Click on "Nicht dekodiert" (do not mark any file)
2. From "Dekodieren und schneiden" choose "Beste Cutlist"
3. A dialog pops up asking if all files should be processed. Choose "Yes".
4. Good luck :)

[synOTR](https://synotr.geimist.eu/) seems to do exactly what you are looking for but it is made for synology diskstation.

**Comment by tango25001** [comment]
Thanky you,

but unfortunately I am using a headless Raspi with Aria2 Downloadmanager, right now. I just want to start the filedownload in my browser and enjoy the decoded and cut file with the best rated cut list. Thats what I am looking for :-) thank you anyway

**Comment by gCurse** [comment]
Maybe [RPi-OTR-Tool](https://www.otrforum.com/showthread.php?75486-RPi-OTR-Tool) fits your needs.

Closing this issue.
