### ISSUE TITLE
Results screen not shown

### ISSUE THREAD

**Issue by fermat2a** [EinApfelBaum/otr-verwaltung3p#88]
On Ubuntu 19.10 showing the result screen after decrypting and cutting videos is not shown. Instead I see following output:

```
Traceback (most recent call last):
  File "/home/fermat/otr-verwaltung3p/otrverwaltung/gui/MainWindow.py", line 553, in on_button_show_conclusion_clicked
    self.app.conclusions_manager.show_conclusions()
  File "/home/fermat/otr-verwaltung3p/otrverwaltung/conclusions.py", line 94, in show_conclusions
    self.app.config.get('general', 'folder_archive'))
  File "/home/fermat/otr-verwaltung3p/otrverwaltung/gui/ConclusionDialog.py", line 91, in _run
    self.combobox_archive.fill(archive_directory)
  File "/home/fermat/otr-verwaltung3p/otrverwaltung/gui/widgets/FolderChooserComboBox.py", line 61, in fill
    image = Gtk.IconTheme.get_default().load_icon('folder', 16, Gtk.IconLookupFlags.USE_BUILTIN)
```

The idon "folder" does not exist. I changed this to folder-symbolic and it worked again. Pull Request will follow...

**Comment by gCurse** [comment]
The icon name "folder" is part of the Icon Theme Specification (freedesktop.org, also used by Gnome and KDE et al.).
Please make sure you are not using an icon theme that does not follow this standard.

As I am aware that there are incomplete/non-standard icon themes, it may be a good idea to find a way to circumvent such an exception. So if you want to contribute feel free to find a way.

This comment applies to #89, too.

**Comment by gCurse** [comment]
I now setup a VM with Ubuntu 19.10 (minimal installation) and then installed otrv3p. I then cut a video manually and a second time "best cutlist" an did not get any error.

If you have any further insight into your problem, please report. For now I close this issue and the PR.
